version:	"11-Sep-2022"
copyright:	"2022"
author:		"Muhammad Hilman Al Ayubi"
title:		"OS222: Operating Systems 2022-2"
githublink:	"https://github.com/al-ayubi2020/os222"
myloglink:	"/TXT/mylog.txt"
markdown:	kramdown

