version:	"11-Sep-2022"
copyright:	"2022"
author:		"Muhammad Hilman Al Ayubi"
title:		"OS222: Operating Systems 2022-2"
githublink:	"https://github.com/al-ayubi2020/os222"
myloglink:	"/TXT/mylog.txt"
myupdatelink:	"/TXT/myupdate.txt"
markdown:	kramdown
tarballlink:	"https://os.vlsm.org/Log/al-ayubi2020.tar.bz2.txt"
